using System;
using UnityEngine;
using UnityEngine.Audio;
using UnityEngine.EventSystems;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

public class TitleManager : MonoBehaviour
{
    private TitleSceneManager titleSceneManager;
    public static TitleManager Instance { get; private set; }
    [SerializeField] private AudioMixer audioMixer;

    public Sprite titleSprite;
    public Sprite titleSprite2;
    public Sprite titleBackSprite;
    public Sprite titleBackSprite2;

    // ï¿½yï¿½Ç‰ï¿½ï¿½zAudioSourceï¿½Rï¿½ï¿½ï¿½|ï¿½[ï¿½lï¿½ï¿½ï¿½gï¿½Ö‚ÌQï¿½ï¿½
    public AudioSource audioSource;
    // ï¿½yï¿½Ç‰ï¿½ï¿½zï¿½Jï¿½[ï¿½\ï¿½ï¿½ï¿½Ú“ï¿½SE
    public AudioClip moveSE;
    // ï¿½yï¿½Ç‰ï¿½ï¿½zï¿½ï¿½ï¿½ï¿½SE
    public AudioClip decideSE;

    public Button[] menuButtons;                    // ï¿½ï¿½ï¿½jï¿½ï¿½ï¿½[ï¿½{ï¿½^ï¿½ï¿½ï¿½ï¿½ï¿½iï¿½[ï¿½ï¿½ï¿½ï¿½zï¿½ï¿½
    public Image cursorImage;                       // ï¿½Jï¿½[ï¿½\ï¿½ï¿½ï¿½æ‘œï¿½iImageï¿½Rï¿½ï¿½ï¿½|ï¿½[ï¿½lï¿½ï¿½ï¿½gï¿½j
    public float cursorOffset = 50f;                // ï¿½Jï¿½[ï¿½\ï¿½ï¿½ï¿½Æƒ{ï¿½^ï¿½ï¿½ï¿½ÌŠÔ‚ÌƒIï¿½tï¿½Zï¿½bï¿½gï¿½iï¿½ï¿½ï¿½ï¿½ï¿½j
    private int currentSelectedButtonIndex = 0;     // ï¿½ï¿½ï¿½İ‘Iï¿½ğ’†‚Ìƒ{ï¿½^ï¿½ï¿½ï¿½ÌƒCï¿½ï¿½ï¿½fï¿½bï¿½Nï¿½X

    // AudioMixerï¿½ï¿½Exposed Parameterï¿½ï¿½ï¿½Æˆï¿½vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    private const string BGM_VOLUME_PARAM = "BGMVolume";
    private const string SE_VOLUME_PARAM = "SEVolume";

    private void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }
        Instance = this;
        DontDestroyOnLoad(gameObject);
    }

    void Start()
    {
        titleSceneManager = GameObject.Find("TitleSceneManager").GetComponent<TitleSceneManager>();
        //// ï¿½Jï¿½[ï¿½\ï¿½ï¿½ï¿½æ‘œï¿½ï¿½ï¿½Åï¿½ï¿½Í”ï¿½\ï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½
        //if (cursorImage != null)
        //{
        //    cursorImage.gameObject.SetActive(false);
        //}

        // ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½{ï¿½^ï¿½ï¿½ï¿½ï¿½İ’è‚µï¿½Aï¿½Jï¿½[ï¿½\ï¿½ï¿½ï¿½ï¿½zï¿½u
        if (menuButtons.Length > 0)
        {
            SelectButton(0);
        }


        if (GameManager.Instance.IsGameClear)
        {
            titleSceneManager.logoImage.sprite = titleSprite2;
            titleSceneManager.titleBackImage.sprite = titleBackSprite2;
        }
        else
        {
            titleSceneManager.logoImage.sprite = titleSprite;
            titleSceneManager.titleBackImage.sprite = titleBackSprite;
        }
    }

    // ï¿½yï¿½Ç‰ï¿½ï¿½zï¿½ï¿½ï¿½Ê‰ï¿½ï¿½ï¿½ï¿½Äï¿½ï¿½ï¿½ï¿½ï¿½wï¿½ï¿½ï¿½pï¿½[ï¿½Öï¿½
    private void PlaySound(AudioClip clip)
    {
        if (audioSource != null && clip != null)
        {
            audioSource.PlayOneShot(clip); // ï¿½ï¿½ï¿½İÄï¿½ï¿½ï¿½ï¿½Ì‰ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½Aï¿½dï¿½Ë‚ÄÄï¿½ï¿½ï¿½ï¿½ï¿½
        }
    }

    void Update()
    {
        // ï¿½ï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½ï¿½
        if (Input.GetKeyDown(KeyCode.UpArrow))
        {
            currentSelectedButtonIndex--;
            if (currentSelectedButtonIndex < 0)
            {
                currentSelectedButtonIndex = menuButtons.Length - 1; // ï¿½ï¿½Ô‰ï¿½ï¿½Ìƒ{ï¿½^ï¿½ï¿½ï¿½Öƒï¿½ï¿½[ï¿½v
            }
            SelectButton(currentSelectedButtonIndex);
            PlaySound(moveSE);
        }

        // ï¿½ï¿½ï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½ï¿½
        if (Input.GetKeyDown(KeyCode.DownArrow))
        {
            currentSelectedButtonIndex++;
            if (currentSelectedButtonIndex >= menuButtons.Length)
            {
                currentSelectedButtonIndex = 0; // ï¿½ï¿½Ôï¿½Ìƒ{ï¿½^ï¿½ï¿½ï¿½Öƒï¿½ï¿½[ï¿½v
            }
            SelectButton(currentSelectedButtonIndex);
            PlaySound(moveSE);
        }

        // Spaceï¿½Lï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½ï¿½
        if (Input.GetKeyDown(KeyCode.Space))
        {
            // ï¿½ï¿½ï¿½İ‘Iï¿½ğ’†‚Ìƒ{ï¿½^ï¿½ï¿½ï¿½ï¿½OnClickï¿½Cï¿½xï¿½ï¿½ï¿½gï¿½ï¿½ï¿½ï¿½ï¿½s
            if (menuButtons.Length > currentSelectedButtonIndex)
            {
                menuButtons[currentSelectedButtonIndex].onClick.Invoke();
            }
            PlaySound(decideSE);
        }
    }

    // ï¿½{ï¿½^ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½Aï¿½Jï¿½[ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Öï¿½
    void SelectButton(int index)
    {
        if (index < 0 || index >= menuButtons.Length) return;

        // ï¿½Ü‚ï¿½ï¿½Sï¿½Ä‚Ìƒ{ï¿½^ï¿½ï¿½ï¿½Ìƒnï¿½Cï¿½ï¿½ï¿½Cï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½iï¿½Oï¿½Ì‚ï¿½ï¿½ßj
        // EventSystem.current.SetSelectedGameObject(null);

        // ï¿½wï¿½è‚³ï¿½ê‚½ï¿½{ï¿½^ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½Ô‚É‚ï¿½ï¿½ï¿½
        EventSystem.current.SetSelectedGameObject(menuButtons[index].gameObject);
        currentSelectedButtonIndex = index; // ï¿½ï¿½ï¿½İ‚Ì‘Iï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½fï¿½bï¿½Nï¿½Xï¿½ï¿½ï¿½Xï¿½V

        // ï¿½Jï¿½[ï¿½\ï¿½ï¿½ï¿½æ‘œï¿½ï¿½Lï¿½ï¿½ï¿½É‚ï¿½ï¿½Aï¿½Ê’uï¿½ğ’²ï¿½
        if (cursorImage != null)
        {
            cursorImage.gameObject.SetActive(true);
            // ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½{ï¿½^ï¿½ï¿½ï¿½ï¿½RectTransformï¿½ï¿½ï¿½æ“¾
            RectTransform buttonRect = menuButtons[index].GetComponent<RectTransform>();

            // ï¿½Jï¿½[ï¿½\ï¿½ï¿½ï¿½ÌˆÊ’uï¿½ï¿½ï¿½{ï¿½^ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½Éİ’ï¿½
            // ï¿½{ï¿½^ï¿½ï¿½ï¿½Ìï¿½ï¿½[ï¿½ï¿½ï¿½ç¶ï¿½ï¿½cursorOffsetï¿½ï¿½ï¿½Ú“ï¿½
            float xPos = buttonRect.position.x - buttonRect.rect.width / 2f - cursorOffset;
            float yPos = buttonRect.position.y; // ï¿½{ï¿½^ï¿½ï¿½ï¿½Æ“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½

            cursorImage.rectTransform.position = new Vector3(xPos, yPos, 0);
        }
    }

    // ï¿½}ï¿½Eï¿½Xï¿½Jï¿½[ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½{ï¿½^ï¿½ï¿½ï¿½Éï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÉŒÄ‚Î‚ï¿½ï¿½Cï¿½xï¿½ï¿½ï¿½gï¿½nï¿½ï¿½ï¿½hï¿½ï¿½
    // ï¿½ï¿½ï¿½ï¿½É‚ï¿½ï¿½Aï¿½}ï¿½Eï¿½Xï¿½ï¿½ï¿½ï¿½Å‚ï¿½ï¿½Jï¿½[ï¿½\ï¿½ï¿½ï¿½æ‘œï¿½ï¿½ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½æ‚¤ï¿½É‚È‚ï¿½
    public void OnPointerEnterButton(Button hoveredButton)
    {
        for (int i = 0; i < menuButtons.Length; i++)
        {
            if (menuButtons[i] == hoveredButton)
            {
                SelectButton(i); // ï¿½zï¿½oï¿½[ï¿½ï¿½ï¿½ê‚½ï¿½{ï¿½^ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½Ô‚É‚ï¿½ï¿½ï¿½
                break;
            }
        }
    }


    public void StartGame()
    {
        Debug.Log("ï¿½Qï¿½[ï¿½ï¿½ï¿½Xï¿½^ï¿½[ï¿½gï¿½I");
        // (ï¿½fï¿½oï¿½bï¿½Oï¿½Fï¿½Iï¿½vï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½İ’ï¿½Vï¿½[ï¿½ï¿½ï¿½Ö‘Jï¿½ï¿½)
        SceneManager.LoadScene("Sakamoto");
    }

    public void OpenOption()
    {
        if (titleSceneManager == null)
        {
            Debug.LogError("titleSceneManager ãŒè¦‹ã¤ã‹ã‚Šã¾ã›ã‚“ï¼ˆç ´æ£„ã•ã‚Œã¦ã„ã‚‹å¯èƒ½æ€§ï¼‰");
            return;
        }

        if (titleSceneManager.optionPanel != null)
        {
            titleSceneManager.optionPanel.SetActive(true);
        }
        else
        {
            Debug.LogError("optionPanel ãŒè¦‹ã¤ã‹ã‚Šã¾ã›ã‚“ï¼ˆç ´æ£„ã•ã‚Œã¦ã‚‹å¯èƒ½æ€§ï¼‰");
        }

        this.enabled = false;

        if (titleSceneManager.titleUis != null)
        {
            titleSceneManager.titleUis.SetActive(false);
        }
        else
        {
            Debug.LogError("titleUis ãŒè¦‹ã¤ã‹ã‚Šã¾ã›ã‚“ï¼ˆç ´æ£„ã•ã‚Œã¦ã‚‹å¯èƒ½æ€§ï¼‰");
        }
    }

    public void CloseOption()
    {
        // ï¿½ï¿½Ê‚ï¿½Â‚ï¿½ï¿½ï¿½
        titleSceneManager.optionPanel.SetActive(false);

        // ï¿½Xï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Jï¿½n
        this.enabled = true;

        // ï¿½^ï¿½Cï¿½gï¿½ï¿½UIï¿½ï¿½\ï¿½ï¿½
        titleSceneManager.titleUis.SetActive(true);

        //ï¿½{ï¿½^ï¿½ï¿½ï¿½Ê’uï¿½ï¿½ï¿½ï¿½ï¿½Zï¿½bï¿½g
        //RectTransform buttonRect = menuButtons[0].GetComponent<RectTransform>();
        //float xPos = buttonRect.position.x - buttonRect.rect.width / 2f - cursorOffset;
        //float yPos = buttonRect.position.y; // ï¿½{ï¿½^ï¿½ï¿½ï¿½Æ“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        //cursorImage.rectTransform.position = new Vector3(xPos, yPos, 0);
    }

    public void SetBGMVolume(float volume)
    {
        // volumeï¿½ï¿½ï¿½fï¿½Vï¿½xï¿½ï¿½ï¿½lï¿½É•ÏŠï¿½
        float decibel = Mathf.Log10(volume) * 20f;

        // 0ï¿½Ìê‡
        if (volume == 0f)
        {
            // ï¿½Åï¿½ï¿½lï¿½ï¿½İ’ï¿½
            decibel = -80f;
        }

        // AudioMixerï¿½É’lï¿½ï¿½İ’ï¿½
        audioMixer.SetFloat(BGM_VOLUME_PARAM, decibel);
    }

    public void SetSEVolume(float volume)
    {
        // volumeï¿½ï¿½ï¿½fï¿½Vï¿½xï¿½ï¿½ï¿½lï¿½É•ÏŠï¿½
        float decibel = Mathf.Log10(volume) * 20f;

        // 0ï¿½Ìê‡
        if (volume == 0f)
        {
            // ï¿½Åï¿½ï¿½lï¿½ï¿½İ’ï¿½
            decibel = -80f;
        }

        // AudioMixerï¿½É’lï¿½ï¿½İ’ï¿½
        audioMixer.SetFloat(SE_VOLUME_PARAM, decibel);
    }

    public void ExitGame()
    {
        // Unityï¿½Gï¿½fï¿½Bï¿½^ï¿½[ï¿½Å‚Ì“ï¿½ï¿½ï¿½
        /*  UnityEditor.EditorApplication.isPlaying = false;
         Application.Quit(); */
    }

    public void GetSceneManager()
    {
        titleSceneManager = GameObject.Find("TitleSceneManager").GetComponent<TitleSceneManager>();
        if (GameManager.Instance.IsGameClear)
        {
            titleSceneManager.logoImage.sprite = titleSprite2;
            titleSceneManager.titleBackImage.sprite = titleBackSprite2;
        }
        else
        {
            titleSceneManager.logoImage.sprite = titleSprite;
            titleSceneManager.titleBackImage.sprite = titleBackSprite;
        }
    }
}
